- hosts: k8s_master
  gather_facts: True
  become: True
  tags: init
  vars_files:
    - "ansible_vars_{{ ansible_distribution | lower }}.yml"
    - "ansible_vars_k8s.yml"
  tasks:
    - name: Create kubeadm directory
      file:
        path: /etc/kubernetes/kubeadm
        state: directory
        mode: '0755'

    - name: Populate kubeadm config
      template:
        src: kubeadm-config.j2
        dest: /etc/kubernetes/kubeadm/kubeadm-config.yaml

    - name: Run kubeadm init command here
      become: True
      command: | 
        kubeadm init \
          --config=/etc/kubernetes/kubeadm/kubeadm-config.yaml \
          --upload-certs
      register: kube_out

    - name: print output of kubeadm init
      debug:
        var: kube_out.stdout
        verbosity: 4

    - name: create .kube directory
      become: yes
      become_user: "{{ k8s_user }}"
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ k8s_user }}/.kube/config
        remote_src: yes
        owner: "{{ k8s_user }}"

    - name: Download CNI Calico Yaml
      become: yes
      become_user: "{{ k8s_user }}"
      tags: cni
      get_url:
        url: https://docs.projectcalico.org/v3.9/manifests/calico.yaml
        dest: /home/{{ k8s_user }}/calico.yaml
    # works only for calico
    - name: Replace CNI Calico Pod CIDR
      tags: cni
      replace:
        backup: yes
        path: /home/{{ k8s_user }}/calico.yaml
        regexp: '192.168.0.0/16'
        replace: "{{ pod_cidr }}"

