- hosts: "{{ server_hosts }}"
  become: Yes
  gather_facts: No
  vars:
    myuser: "{{ sudoer | default('ansible') }}"
  tasks:
    - name: create the "{{ myuser }}" user
      user: name={{ myuser }} append=yes state=present create_home=yes shell=/bin/bash

    - name: allow "{{ myuser }}" to have passwordless sudo
      lineinfile:
        create: yes
        dest: /etc/sudoers.d/{{ myuser }}
        line: '{{ myuser }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the {{ myuser }} user
      authorized_key: user={{ myuser }} key="{{item}}"
      with_file:
        - ~/.ssh/tfadmin.pub
