- hosts: "{{ server_hosts }}"
  become: yes
  tasks:
    - name: create the "{{ sudoer }}" user
      user: name={{ sudoer }} append=yes state=present createhome=yes shell=/bin/bash

    - name: allow "{{ sudoer }}" to have passwordless sudo
      lineinfile:
        create: yes
        dest: /etc/sudoers.d/{{ sudoer }}
        line: '{{ sudoer }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the {{ sudoer }} user
      authorized_key: user={{ sudoer }} key="{{item}}"
      with_file:
        - ~/.ssh/lnxa_rsa.pub
